package Widget;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Sendingfromusertowidget {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("sendingmsgfromusertowidget1.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		Thread.sleep(1000);
		ExtentTest test= extent.createTest("Send the msg from user to widget & Right click on msg");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("EXPECTED RESULT:: It should display reply, forward & delete");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying reply, forward & delete");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println();
		driver.close();
		driver1.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		WebElement e1=driver1.findElement(By.xpath("//div[@class='conversation-option-wrapper']"));
		Actions ac=new Actions(driver1);
		ac.moveToElement(e).click(e1).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//div[@class='conversation-option-menu']")).getText();
		Thread.sleep(1000);
		ExtentTest test= extent.createTest("Send the msg from user to widget & Click on drop down");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("Click on user sended msg");
		test.info("Click on drop down");
		test.info("View the page");
		test.info("EXPECTED RESULT:: It should display reply, forward & delete");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying reply, forward & delete");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(1);
		driver.close();
		driver1.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a1=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("1");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a2=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Click on reply for sended msg");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on reply");
		test.info("Send the msg");
		test.info("EXPECTED RESULT:: It should send the reply msg");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Reply");
		test.pass(a4);
		Assert.assertEquals(a1, "sai\n"
				+ "test");
		test.pass(a1);
		Assert.assertEquals(a2, "Sai\n"
				+ "test");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is sending the reply msg");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(2);
		driver.close();
		driver1.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a1=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		String a2=driver1.findElement(By.xpath("//span[@class='chat-reply-close']")).getAttribute("class");
		driver1.findElement(By.xpath("//span[@class='chat-reply-close']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Click on close button in reply");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on reply");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in reply");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Reply");
		test.pass(a4);
		Assert.assertEquals(a1, "sai\n"
				+ "test");
		test.pass(a1);
		Assert.assertEquals(a2, "chat-reply-close");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is clicking on close button in reply");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(3);
		driver.close();
		driver1.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a1=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//div[@id='troopGritConversationBackBtn']")).click();
		Thread.sleep(1000);
		String a3=driver1.findElement(By.xpath("//div[@data-name='abc']")).getAttribute("data-name");
		driver1.findElement(By.xpath("//div[@data-name='abc']")).click();
		String a2=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Click on reply & Come back & Again click on user1");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on reply");
		test.info("Click on back buton");
		test.info("Click on user1 : abcd");
		test.info("View the page");
		test.info("EXPECTED RESULT:: It should not display reply chat in user1");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Reply");
		test.pass(a4);
		Assert.assertEquals(a1, "sai\n"
				+ "test");
		test.pass(a1);
		Assert.assertEquals(a3, "abc");
		test.pass(a3);
		Assert.assertEquals(a2, "");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT:: It is not displaying reply chat in user1");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(4);
		driver.close();
		driver1.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver1.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		String a1=driver1.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).getText();
		driver1.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver1.findElement(By.xpath("//div[@data-username='abc']")).getAttribute("data-username");
		driver1.findElement(By.xpath("//label[@for='forwardUser_19-1']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritConversationBackBtn']")).click();
		Thread.sleep(1000);
		String a2=driver1.findElement(By.xpath("//div[@data-name='abc']")).getAttribute("data-name");
		driver1.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		String a5=driver1.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget user forward the msg to user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on forward");
		test.info("Click on forward button");
		test.info("Select the user1 : sai");
		test.info("Click on send button");
		test.info("Click on back button");
		test.info("Click on user1");
		test.info("View the page");
		test.info("EXPECTED RESULT:: It should display forward symbol for msg in user1");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Forward");
		test.pass(a4);
		Assert.assertEquals(a1, "FRWD");
		test.pass(a1);
		Assert.assertEquals(a3, "abc");
		test.pass(a3);
		Assert.assertEquals(a2, "abc");
		test.pass(a2);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying forward symbol for msg in user1");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(5);
		driver.close();
		driver1.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='forward']")).getText();
		driver.findElement(By.xpath("//a[@data-action='forward']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='forwardMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//div[@data-username='abc']")).getAttribute("data-username");
		driver.findElement(By.xpath("//label[@for='forwardUser_19-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='modalForwardSendMessageBtn']")).click();
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		String a5=driver1.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User send forward msg to widget user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on forward");
		test.info("Click on forward button");
		test.info("Select the user : abc");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("View the page");
		test.info("EXPECTED RESULT:: It should display forward symbol for msg in user");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a4, "Forward");
		test.pass(a4);
		Assert.assertEquals(a1, "FRWD");
		test.pass(a1);
		Assert.assertEquals(a3, "abc");
		test.pass(a3);
		Assert.assertEquals(a5, "forward-conversation-label-icon");
		test.pass(a5);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying forward symbol for msg in user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(6);
		driver.close();
		driver1.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("sai");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='delete']")).getText();
		driver.findElement(By.xpath("//a[@data-action='delete']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//input[@id='deleteMessage_12124']")).getAttribute("id");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).click();
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='sai']")).click();
		Thread.sleep(1000);
		WebElement e1=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver1);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//a[@data-action='delete']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a6=driver1.findElement(By.xpath("//input[@id='deleteMessage_12124']")).getAttribute("id");
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User delete msg in widget user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : sai");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on yes button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display deleted msg in widget user");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a4, "Delete");
		test.pass(a4);
		Assert.assertEquals(a5, "deleteMessage_12124");
		test.pass(a5);
		Assert.assertEquals(a1, "DEL");
		test.pass(a1);
		Assert.assertEquals(a3, "Yes");
		test.pass(a3);
		Assert.assertEquals(a6, "deleteMessage_12124");
		test.pass(a6);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying deleted msg in widget user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(7);
		driver.close();
		driver1.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:3000/user/submit-app");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='delete']")).getText();
		driver.findElement(By.xpath("//a[@data-action='delete']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//input[@id='deleteMessage_12193']")).getAttribute("id");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a2=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:8083");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath1");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		//driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e1=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver1);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//a[@data-action='delete']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a6=driver1.findElement(By.xpath("//input[@id='deleteMessage_12193']")).getAttribute("id");
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget User delete msg in user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:3000/user/submit-app");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on user : sharath");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on yes button");
		test.info("Open incognito");
		test.info("Enter URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on widget user : abc");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display deleted msg in web user");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Delete");
		test.pass(a4);
		Assert.assertEquals(a5, "deleteMessage_12193");
		test.pass(a5);
		Assert.assertEquals(a1, "DEL");
		test.pass(a1);
		Assert.assertEquals(a3, "YES");
		test.pass(a3);
		Assert.assertEquals(a2, "Message Deleted!");
		test.pass(a2);
		Assert.assertEquals(a6, "deleteMessage_12193");
		test.pass(a6);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying deleted msg in web user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(8);
		driver.close();
		driver1.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("dooo");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='testing']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='recall']")).getText();
		driver.findElement(By.xpath("//a[@data-action='recall']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//div[@class='recall-conversation-text']")).getText();
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("testing");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='dooo']")).click();
		Thread.sleep(1000);
		String a7=driver1.findElement(By.xpath("//div[@class='recall-conversation-text']")).getText();
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User recall msg in widget user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : dooo");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : testing");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on recall");
		test.info("Click on recall button");
		test.info("Click on yes button");
		test.info("Open incognito");
		test.info("Enter URL : http://192.168.2.55:3000/user/submit-app");
		test.info("Click on on-site monitoring");
		test.info("Enter username : testing");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : dooo");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display recalled msg in widget user");
		Assert.assertEquals(a, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Recall\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a4, "Recall");
		test.pass(a4);
		Assert.assertEquals(a1, "RECALL");
		test.pass(a1);
		Assert.assertEquals(a3, "Yes");
		test.pass(a3);
		Assert.assertEquals(a8, "You recalled this message");
		test.pass(a8);
		Assert.assertEquals(a7, "This message was recalled");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying recalled msg in widget user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(9);
		driver.close();
		driver1.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:3000/user/submit-app");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("dooo");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='recall']")).getText();
		driver.findElement(By.xpath("//a[@data-action='recall']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a6=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		String a8=driver.findElement(By.xpath("//div[@class='recall-conversation-text']")).getText();
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:8083");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("abc");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='dooo']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		String a7=driver1.findElement(By.xpath("//div[@class='recall-conversation-text']")).getText();
		driver1.findElement(By.xpath("//div[@class='recall-conversation-text']"));
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget User recall msg in user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:3000/user/submit-app");
		test.info("Enter username : dooo");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on recall");
		test.info("Click on recall button");
		test.info("Click on yes button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on widget user : dooo");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display recall msg in web user");
		Assert.assertEquals(a, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Recall\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Recall");
		test.pass(a4);
		Assert.assertEquals(a1, "RECALL");
		test.pass(a1);
		Assert.assertEquals(a3, "YES");
		test.pass(a3);
		Assert.assertEquals(a6, "Message Recalled!");
		test.pass(a6);
		Assert.assertEquals(a8, "You recalled this message");
		test.pass(a8);
		Assert.assertEquals(a7, "This message was recalled");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying recall msg in web user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(10);
		driver.close();
		driver1.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("abcde");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='edit']")).getText();
		driver.findElement(By.xpath("//a[@data-action='edit']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@class='chat-edit-message-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("1");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='abcde']")).click();
		Thread.sleep(1000);
		String a7=driver1.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a3=driver1.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User edit the msg in widget user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : abcde");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on edit");
		test.info("Enter text : 1");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL : http://192.168.2.55:3000/user/submit-app");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : sai");
		test.info("View the msg");
		test.info("EXPECTED RESULT:: It should display recalled msg in widget user");
		Assert.assertEquals(a, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Recall\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a4, "Edit");
		test.pass(a4);
		Assert.assertEquals(a5, "Me\n"
				+ "test");
		test.pass(a5);
		Assert.assertEquals(a8, "edited-conversation-icon");
		test.pass(a8);
		Assert.assertEquals(a1, "test1");
		test.pass(a1);
		Assert.assertEquals(a7, "edited-conversation-icon");
		test.pass(a7);
		Assert.assertEquals(a3, "test1");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying recalled msg in widget user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(11);
		driver.close();
		driver1.close();
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:3000/user/submit-app");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("babu");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abc']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='edit']")).getText();
		driver.findElement(By.xpath("//a[@data-action='edit']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='chat-edit-message-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("1");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a5=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:8083");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("abc");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='babu']")).click();
		Thread.sleep(1000);
		Thread.sleep(2000);
		String a7=driver.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a3=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget User edit the msg in user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:3000/user/submit-app");
		test.info("Enter username : babu");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user ; abc");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on edit");
		test.info("Enter text : 1");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Enter username : abc");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : babu");
		test.info("View the msg");
		test.info("EXPECTED RESULT:: It should display edited msg in web user");
		Assert.assertEquals(a, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Recall\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a4, "Edit");
		test.pass(a4);
		Assert.assertEquals(a1, "Me\n"
				+ "test");
		test.pass(a1);
		Assert.assertEquals(a8, "edited-conversation-icon");
		test.pass(a8);
		Assert.assertEquals(a5, "test1");
		test.pass(a5);
		Assert.assertEquals(a7, "edited-conversation-icon");
		test.pass(a7);
		Assert.assertEquals(a3, "test1");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying edited msg in web user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(12);
		driver.close();
		driver1.close();
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("abcde");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abcd']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abcd");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='abcde']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a5=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a10=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(2000);
		//Web user recall
		WebElement e1=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='recall']")).getText();
		driver.findElement(By.xpath("//a[@data-action='recall']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='recallConfirmationYesBtn']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		String a7=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User reply the msg & recall it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : abcde");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abcd");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL : http://192.168.2.55:3000/user/submit-app");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abcd");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : abcde");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on reply");
		test.info("Enter text");
		test.info("Click on send button");
		test.info("From user right click on user sent msg");
		test.info("Click on recall");
		test.info("Click on recall button");
		test.info("Click on yes button");
		test.info("View the msg of reply");
		test.info("EXPECTED RESULT:: It should display recalled msg & in reply it should recall the msg for both the users");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a5, "Reply");
		test.pass(a5);
		Assert.assertEquals(a10, "abcde\n"
				+ "test");
		test.pass(a10);
		Assert.assertEquals(a9, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Recall\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a9);
		Assert.assertEquals(a4, "Recall");
		test.pass(a4);
		Assert.assertEquals(a1, "RECALL");
		test.pass(a1);
		Assert.assertEquals(a3, "Yes");
		test.pass(a3);
		Assert.assertEquals(a8, "You\n"
				+ "You recalled this message");
		test.pass(a8);
		Assert.assertEquals(a7, "Abcde\n"
				+ "You recalled this message");
		test.pass(a7);
		test.log(Status.FAIL,"ACTUAL RESULT:: It is displaying recalled msg & in reply it is recalling the msg for both the users but it is displaying toast as you recalled this msg for widget user");
		test.log(Status.FAIL,"Test Case:: TestCase FAILED");
		System.out.println(13);
		driver.close();
		driver1.close();
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:3000/user/submit-app");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("babu");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='dooo']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:8083");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("dooo");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='babu']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a5=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a10=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e1=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='recall']")).getText();
		driver.findElement(By.xpath("//a[@data-action='recall']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='recallMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a6=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(1000);
		Thread.sleep(2000);
		String a8=driver.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		String a7=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget User reply the msg & recall it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:3000/user/submit-app");
		test.info("Enter username : babu");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on user : dooo");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on recall");
		test.info("Click on recall button");
		test.info("Click on yes button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Enter username : dooo");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on widget user : babu");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display recalled msg & in reply it should recall the msg for both the users");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a5, "Reply");
		test.pass(a5);
		Assert.assertEquals(a10, "babu\n"
				+ "test");
		test.pass(a10);
		Assert.assertEquals(a9, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Recall\n"
				+ "Delete");
		test.pass(a9);
		Assert.assertEquals(a4, "Recall");
		test.pass(a4);
		Assert.assertEquals(a1, "RECALL");
		test.pass(a1);
		Assert.assertEquals(a3, "YES");
		test.pass(a3);
		Assert.assertEquals(a6, "Message Recalled!");
		test.pass(a6);
		Assert.assertEquals(a8, "You\n"
				+ "You recalled this message");
		test.pass(a8);
		Assert.assertEquals(a7, "Babu\n"
				+ "This message was recalled");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying recalled msg & in reply it is recalling the msg for both the users");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(14);
		driver.close();
		driver1.close();
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("dooo");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abcd']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abcd");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='dooo']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a5=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a10=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(2000);
		//Web user recall
		WebElement e1=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='delete']")).getText();
		driver.findElement(By.xpath("//a[@data-action='delete']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='deleteConfirmationYesBtn']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		String a7=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User reply the msg & delete it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : dooo");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abcd");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL : http://192.168.2.55:3000/user/submit-app");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abcd");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : abcde");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on reply");
		test.info("Enter text");
		test.info("Click on send button");
		test.info("From user right click on user sent msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on yes button");
		test.info("View the msg of reply");
		test.info("EXPECTED RESULT:: It should display deleted msg & in reply it should delete the msg only for user");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a5, "Reply");
		test.pass(a5);
		Assert.assertEquals(a10, "dooo\n"
				+ "test");
		test.pass(a10);
		Assert.assertEquals(a9, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Recall\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a9);
		Assert.assertEquals(a4, "Delete");
		test.pass(a4);
		Assert.assertEquals(a1, "DEL");
		test.pass(a1);
		Assert.assertEquals(a3, "Yes");
		test.pass(a3);
		Assert.assertEquals(a8, "You\n"
				+ "You deleted this message");
		test.pass(a8);
		Assert.assertEquals(a7, "Dooo\n"
				+ "test");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying deleted msg & in reply it is deleting the msg only for user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(15);
		driver.close();
		driver1.close();
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:3000/user/submit-app");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("dooo");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='css']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:8083");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("css");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='dooo']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a5=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a10=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e1=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='delete']")).getText();
		driver.findElement(By.xpath("//a[@data-action='delete']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).getText();
		driver.findElement(By.xpath("//span[@id='deleteMessageSendBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(1000);
		String a6=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(1000);
		Thread.sleep(2000);
		String a8=driver.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		String a7=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-text conversation-message-reply-wrapper']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget User reply the msg & delete it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:3000/user/submit-app");
		test.info("Enter username : dooo");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on user : css");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on delete");
		test.info("Click on delete button");
		test.info("Click on yes button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Enter username : css");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on widget user : dooo");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display deleted msg & in reply it should delete the msg only for widget user");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a5, "Reply");
		test.pass(a5);
		Assert.assertEquals(a10, "dooo\n"
				+ "test");
		test.pass(a10);
		Assert.assertEquals(a9, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Recall\n"
				+ "Delete");
		test.pass(a9);
		Assert.assertEquals(a4, "Delete");
		test.pass(a4);
		Assert.assertEquals(a1, "DEL");
		test.pass(a1);
		Assert.assertEquals(a3, "YES");
		test.pass(a3);
		Assert.assertEquals(a6, "Message Deleted!");
		test.pass(a6);
		Assert.assertEquals(a8, "You\n"
				+ "You deleted this message");
		test.pass(a8);
		Assert.assertEquals(a7, "Dooo\n"
				+ "test");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying deleted msg & in reply It is deleting the msg only for widget user");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(16);
		driver.close();
		driver1.close();
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//input[@id='username']")).sendKeys("babu");
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abcd']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:3000/user/submit-app");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("abcd");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='babu']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a5=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a10=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(2000);
		//Web user recall
		WebElement e1=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='edit']")).getText();
		driver.findElement(By.xpath("//a[@data-action='edit']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@class='chat-edit-message-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("1");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a6=driver1.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a2=driver1.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a8=driver.findElement(By.xpath("//div[@class='conversation-message-reply-wrapper conversation-message-reply-text']")).getText();
		String a7=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-wrapper conversation-message-reply-text']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("User reply the msg & delete it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:8083");
		test.info("Enter username : dooo");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on widget user : abcd");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL : http://192.168.2.55:3000/user/submit-app");
		test.info("Click on on-site monitoring");
		test.info("Enter username : abcd");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on user : abcde");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on reply");
		test.info("Enter text");
		test.info("Click on send button");
		test.info("From user right click on user sent msg");
		test.info("Click on edit");
		test.info("Enter text");
		test.info("Click on send button");
		test.info("View the msg of reply");
		test.info("EXPECTED RESULT:: It should display edited msg & in reply for both the users it should change the edited msg");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Delete");
		test.pass(a);
		Assert.assertEquals(a5, "Reply");
		test.pass(a5);
		Assert.assertEquals(a10, "babu\n"
				+ "test");
		test.pass(a10);
		Assert.assertEquals(a9, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Recall\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a9);
		Assert.assertEquals(a4, "Edit");
		test.pass(a4);
		Assert.assertEquals(a11, "Me\n"
				+ "test");
		test.pass(a11);
		Assert.assertEquals(a3, "edited-conversation-icon");
		test.pass(a3);
		Assert.assertEquals(a1, "test1");
		test.pass(a1);
		Assert.assertEquals(a6, "edited-conversation-icon");
		test.pass(a6);
		Assert.assertEquals(a2, "test1");
		test.pass(a2);
		Assert.assertEquals(a8, "You\n"
				+ "test1");
		test.pass(a8);
		Assert.assertEquals(a7, "Babu\n"
				+ "test1");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying edited msg & in reply for both the users it is changing the edited msg");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(17);
		driver.close();
		driver1.close();
	}
	@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		ChromeOptions options = new ChromeOptions();
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:3000/user/submit-app");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='troopGritEntryBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginUsernameInput']")).sendKeys("babu");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='troopGritLoginPasswordInput']")).sendKeys("123456");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='troopGritLoginBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='abcde']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("test");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		Thread.sleep(1000);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		ChromeDriver driver1 = new ChromeDriver();
		options.addArguments("--incognito");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		Thread.sleep(1000);
		driver1.get("http://192.168.2.55:8083");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("abcde");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver1.findElement(By.xpath("//div[@data-name='babu']")).click();
		Thread.sleep(1000);
		WebElement e=driver1.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac=new Actions(driver1);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		String a=driver1.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a5=driver1.findElement(By.xpath("//a[@data-action='reply']")).getText();
		driver1.findElement(By.xpath("//a[@data-action='reply']")).click();
		Thread.sleep(1000);
		String a10=driver1.findElement(By.xpath("//div[@class='chat-reply-message-wrapper']")).getText();
		driver1.findElement(By.xpath("//span[@class='message-input']")).sendKeys("test");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e1=driver.findElement(By.xpath("//span[@class='received-message-text']"));
		Actions ac1=new Actions(driver);
		ac1.contextClick(e1).perform();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//nav[@id='context-menu']")).getText();
		String a4=driver.findElement(By.xpath("//a[@data-action='edit']")).getText();
		driver.findElement(By.xpath("//a[@data-action='edit']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@class='chat-edit-message-wrapper']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='troop-grit-message-input']")).sendKeys("1");
		driver.findElement(By.xpath("//span[@id='troopGritSendMessageBtn']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a1=driver.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a6=driver1.findElement(By.xpath("//span[@class='edited-conversation-icon']")).getAttribute("class");
		String a2=driver1.findElement(By.xpath("//span[@class='received-message-text']")).getText();
		String a8=driver.findElement(By.xpath("//div[@class='conversation-message-reply-wrapper conversation-message-reply-text']")).getText();
		String a7=driver1.findElement(By.xpath("//div[@class='conversation-message-reply-wrapper conversation-message-reply-text']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test= extent.createTest("Widget User reply the msg & edit it");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("http://192.168.2.55:3000/user/submit-app");
		test.info("Enter username : babu");
		test.info("Enter password : 123456");
		test.info("Click on login");
		test.info("Click on user : abcde");
		test.info("Enter text : test");
		test.info("Click on send button");
		test.info("Click on user sended msg");
		test.info("Right click on that msg");
		test.info("Click on edit");
		test.info("Enter text");
		test.info("Click on send button");
		test.info("Open incognito");
		test.info("Enter URL");
		test.info("Enter username : abcde");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on widget user : babu");
		test.info("Select the msg & View it");
		test.info("EXPECTED RESULT:: It should display edit the msg & in reply for both the users it should change the edited msg");
		Assert.assertEquals(a, "Reply\n"
				+ "Forward\n"
				+ "Copy\n"
				+ "Delete\n"
				+ "Info");
		test.pass(a);
		Assert.assertEquals(a5, "Reply");
		test.pass(a5);
		Assert.assertEquals(a10, "babu\n"
				+ "test");
		test.pass(a10);
		Assert.assertEquals(a9, "Reply\n"
				+ "Edit\n"
				+ "Forward\n"
				+ "Recall\n"
				+ "Delete");
		test.pass(a9);
		Assert.assertEquals(a4, "Edit");
		test.pass(a4);
		Assert.assertEquals(a11, "Me\n"
				+ "test");
		test.pass(a11);
		Assert.assertEquals(a3, "edited-conversation-icon");
		test.pass(a3);
		Assert.assertEquals(a1, "test1");
		test.pass(a1);
		Assert.assertEquals(a6, "edited-conversation-icon");
		test.pass(a6);
		Assert.assertEquals(a2, "test1");
		test.pass(a2);
		Assert.assertEquals(a8, "You\n"
				+ "test1");
		test.pass(a8);
		Assert.assertEquals(a7, "Babu\n"
				+ "test1");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT:: It is displaying edit the msg & in reply for both the users it is changing the edited msg");
		test.log(Status.PASS,"Test Case:: TestCase PASSED");
		System.out.println(18);
		driver.close();
		driver1.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
